FROM php:7.4.33-fpm

RUN apt-get update && apt-get install -y \
    libzip-dev \
    zlib1g-dev \
    libpng-dev \
    libjpeg-dev \
    libfreetype6-dev \
    libssl-dev \
    libmcrypt-dev \
    && docker-php-ext-configure gd \
    && docker-php-ext-install -j$(nproc) gd mysqli pdo_mysql zip opcache

# RUN pecl install mongodb-1.7.4 \
#     && docker-php-ext-enable mongodb

RUN curl -sS https://getcomposer.org/installer | php  && mv composer.phar /usr/local/bin/composer

